export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children })
{
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="calculator.css" />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
